#!/bin/bash

printf "Running pre-commit hook... 🚀 \n\n"

# Command to run before committing
docker exec app composer test

# shellcheck disable=SC2181
# If the command fails, exit with a non-zero status to abort the commit
if [ $? -ne 0 ]; then
    printf "Pre-commit hook failed. Fix the issues and try again 🛑 \n\n"
    exit 1
fi

printf "Pre-commit hook completed! ✅  \n\n"
