#!/bin/bash

echo "Running pre-commit hook..."

# Command to run before committing
docker exec app composer pre-commit

# If the command fails, exit with a non-zero status to abort the commit
if [ $? -ne 0 ]; then
    echo "Pre-commit hook failed. Fix the issues and try again."
    exit 1
fi

echo "Pre-commit hook completed!"
